### ISSUE TITLE
Can't adjust brightness of second monitor

### ISSUE THREAD

**Issue by adius** [jmstacey/screenbrightness#10]
It shows following error message:

    screenbrightness: failed to set brightness of display 0xb409fb5 (error -536870201)

**Comment by rbugajewski** [comment]
With two displays and OS X 10.10.3 I can’t adjust any of them:

```
➜  ~  screenbrightness -l
display 0: main display, ID 0x4249987
screenbrightness: failed to get brightness of display 0x4249987 (error -536870201)display 1: ID 0x4249980
screenbrightness: failed to get brightness of display 0x4249980 (error -536870201)%
```

When trying to set the brightness of a specific display I get a similar error message:

```
➜  ~  screenbrightness -d 0 0.1
screenbrightness: failed to set brightness of display 0x4249987 (error -536870201)%                      ➜  ~  screenbrightness -d 1 0.1
screenbrightness: failed to set brightness of display 0x4249980 (error -536870201)%
```

When I don’t use the display parameter I also get the same error message:

```
➜  ~  screenbrightness 1
screenbrightness: failed to set brightness of display 0x4249987 (error -536870201)screenbrightness: failed to set brightness of display 0x4249980 (error -536870201)%
```

**Comment by jmstacey** [comment]
Closing this issue -- please re-open on the upstream repo here: https://github.com/nriley/brightness. Please re-open there if this bug is still present in the latest version.
