### ISSUE TITLE
Merge repositories with nriley/brightness or clarify attribution

### ISSUE THREAD

**Issue by mattes** [jmstacey/screenbrightness#9]
https://github.com/nriley/brightness

Does it make sense to merge the repos?

**Comment by christianbundy** [comment]
Is there any movement on this?

**Comment by nriley** [comment]
Not that I know of.  I have been busy but can still spend a few minutes getting stuff set up...

**Comment by jmstacey** [comment]
Closing as fixed. See https://github.com/nriley/brightness/issues/5
